export default function About() {
  return (
    <>
      <h1 className="title"> About Nitzan</h1>
      <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere nulla vitae nulla iaculis, vel interdum augue maximus. Vestibulum a placerat felis. Curabitur eget finibus ante, in posuere metus. Pellentesque maximus nisi ut lacinia ullamcorper. Etiam blandit arcu a consequat tristique. Donec ultricies non metus et posuere. Nullam in diam augue. Fusce placerat lobortis eros, a fringilla felis molestie ac. Phasellus sit amet dui sollicitudin dolor sollicitudin semper sit amet quis ex.
          Vestibulum mi elit, mattis vitae ipsum ut, rhoncus tincidunt libero. Vivamus eu quam tellus. Sed cursus felis vel libero blandit, fermentum porttitor mi porttitor. Nulla cursus mauris sit amet lobortis lacinia. Nulla commodo metus in eros rutrum, ut ultricies dui vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et metus eleifend, ornare ex non, sagittis risus. Fusce varius convallis orci eu aliquet. In ornare at ligula quis elementum. Donec elementum mollis odio in tincidunt. Curabitur sit amet mollis eros. Suspendisse consequat vestibulum porttitor. Fusce vitae libero ultrices, rhoncus massa id, lacinia tortor. Donec dictum sem nec ultrices efficitur.
          In a est ultrices, tempus est sit amet, porttitor sem. Nullam sem urna, aliquam in maximus nec, pulvinar eu nunc. Fusce ut massa sit amet elit vulputate rhoncus. Sed semper lacinia blandit. Vestibulum lorem ante, elementum ac ante sit amet, scelerisque bibendum neque. Ut accumsan consequat finibus. Ut in egestas ligula. Fusce tincidunt lacus quis porta tristique. Fusce eget massa purus. Pellentesque neque mauris, interdum nec lobortis nec, cursus at lacus.
          Donec vulputate rhoncus leo, vitae faucibus nisi blandit sit amet. Ut eget maximus orci, ac ullamcorper dui. Proin ligula lorem, tincidunt quis metus auctor, maximus ornare ligula. Curabitur vulputate ullamcorper facilisis. Nullam euismod a quam sit amet sodales. Integer nunc elit, pharetra sed pulvinar quis, lacinia sit amet felis. Nunc sodales ex a ultricies placerat. Proin pharetra dapibus tortor, porta tristique ex volutpat sit amet. Pellentesque non nibh vel magna sagittis dignissim. Morbi dapibus imperdiet pellentesque. Ut convallis vel tellus eleifend dapibus.
          Cras placerat libero id velit hendrerit, ac mollis metus rhoncus. Maecenas vel accumsan lacus. Nunc congue ultricies sapien a porttitor. Vestibulum fringilla risus ac nibh feugiat, ultrices volutpat dolor tincidunt. Nulla scelerisque ipsum sit amet velit accumsan tincidunt. Aliquam a nibh efficitur, sodales ipsum sed, efficitur dui. In maximus purus in lectus ornare tristique. Nam faucibus porta nulla quis tempus. Etiam tristique sollicitudin euismod. Vivamus hendrerit sem et sem consectetur fermentum. Sed fermentum leo euismod augue tincidunt imperdiet. Aliquam et tempus felis, eu posuere nisl. Nullam a vestibulum dui. Nullam ut arcu id lorem tincidunt ullamcorper.
          Mauris vitae lectus id mi tincidunt bibendum. Sed sollicitudin consequat augue, a posuere tellus eleifend et. Pellentesque pharetra turpis diam, id suscipit nisi tincidunt eu. Etiam id ex vitae libero cursus finibus. Mauris varius ornare augue eget faucibus. Sed sodales magna a eros auctor, ac iaculis nisl sagittis. In gravida nulla aliquam eros sodales, nec tincidunt lectus cursus. Donec sit amet bibendum urna. Nulla sit amet urna at purus rhoncus congue et et magna. Sed volutpat sem ac justo pellentesque, facilisis aliquet lorem mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim fringilla tortor, sed tincidunt lectus facilisis quis. Nam ultrices tincidunt turpis, non tempor dui placerat a.
          Quisque posuere metus a mauris mollis, iaculis lacinia purus accumsan. Integer ut enim et felis commodo aliquet. Curabitur congue erat odio, a gravida justo luctus eget. Donec sollicitudin vestibulum turpis. Curabitur condimentum enim at turpis dapibus, in vehicula leo fringilla. Donec non tortor lacus. Nullam cursus fringilla iaculis. Sed dolor ipsum, congue eget dui quis, varius luctus nisl. Sed massa lacus, sodales non ultricies in, mollis ac dui. Etiam urna elit, convallis non neque quis, mattis pharetra erat. Curabitur at augue quis arcu venenatis tristique quis eu orci. Fusce malesuada iaculis nulla id elementum. Praesent quis nulla lacinia, bibendum dolor quis, finibus diam. Phasellus interdum augue at orci ultricies viverra.
          Donec hendrerit, orci vel vehicula laoreet, enim urna euismod odio, quis gravida mauris nisl nec nulla. In massa velit, hendrerit non nisi at, placerat tempor eros. Aliquam ut mollis nisi, ut congue tellus. Morbi aliquam massa nec arcu mollis tincidunt. Ut sed dui quis massa sollicitudin molestie. Maecenas et dignissim elit. Etiam a placerat elit. Nam tincidunt, massa ac rutrum vulputate, sapien diam blandit sem, vitae dictum enim lacus et nibh. Praesent pharetra gravida vehicula. Aenean purus massa, ullamcorper id felis vestibulum, tincidunt lobortis dui. Vestibulum iaculis pretium nulla. Vestibulum quis ex non dolor bibendum efficitur quis sed tortor. Aliquam viverra erat in tellus venenatis ultricies in facilisis ligula. Integer maximus porta tortor, eget venenatis lorem auctor ut. Praesent tristique nibh eu semper aliquam.
          Proin rhoncus ut orci non rutrum. Fusce sodales lacus ac arcu aliquet consequat. Sed auctor mi eget elementum gravida. Phasellus tempor quis lorem a varius. Curabitur malesuada, eros ac dictum consequat, elit augue tincidunt odio, sit amet malesuada odio tortor eu velit. Fusce tincidunt porta libero, eget aliquam purus lacinia nec. Phasellus rutrum ipsum a blandit cursus.
          Morbi a mauris non neque elementum condimentum. Donec convallis finibus dolor, ut gravida metus. Fusce ut sapien vel turpis cursus dictum id at risus. Ut vulputate libero ligula. Integer mollis, tellus eu pretium interdum, nibh ante eleifend ante, nec imperdiet nisl tortor at dui. Aliquam id ornare erat. Phasellus dignissim feugiat augue, sed aliquet tortor porta ut. Duis condimentum maximus lacus, sit amet fringilla leo cursus a. Proin sed ullamcorper nisl. Sed sagittis nisl nunc, ac maximus risus efficitur in. Praesent suscipit eleifend tellus, ac dignissim ante consequat at. Donec suscipit et risus ac faucibus.
      </p>
      <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere nulla vitae nulla iaculis, vel interdum augue maximus. Vestibulum a placerat felis. Curabitur eget finibus ante, in posuere metus. Pellentesque maximus nisi ut lacinia ullamcorper. Etiam blandit arcu a consequat tristique. Donec ultricies non metus et posuere. Nullam in diam augue. Fusce placerat lobortis eros, a fringilla felis molestie ac. Phasellus sit amet dui sollicitudin dolor sollicitudin semper sit amet quis ex.
          Vestibulum mi elit, mattis vitae ipsum ut, rhoncus tincidunt libero. Vivamus eu quam tellus. Sed cursus felis vel libero blandit, fermentum porttitor mi porttitor. Nulla cursus mauris sit amet lobortis lacinia. Nulla commodo metus in eros rutrum, ut ultricies dui vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et metus eleifend, ornare ex non, sagittis risus. Fusce varius convallis orci eu aliquet. In ornare at ligula quis elementum. Donec elementum mollis odio in tincidunt. Curabitur sit amet mollis eros. Suspendisse consequat vestibulum porttitor. Fusce vitae libero ultrices, rhoncus massa id, lacinia tortor. Donec dictum sem nec ultrices efficitur.
          In a est ultrices, tempus est sit amet, porttitor sem. Nullam sem urna, aliquam in maximus nec, pulvinar eu nunc. Fusce ut massa sit amet elit vulputate rhoncus. Sed semper lacinia blandit. Vestibulum lorem ante, elementum ac ante sit amet, scelerisque bibendum neque. Ut accumsan consequat finibus. Ut in egestas ligula. Fusce tincidunt lacus quis porta tristique. Fusce eget massa purus. Pellentesque neque mauris, interdum nec lobortis nec, cursus at lacus.
          Donec vulputate rhoncus leo, vitae faucibus nisi blandit sit amet. Ut eget maximus orci, ac ullamcorper dui. Proin ligula lorem, tincidunt quis metus auctor, maximus ornare ligula. Curabitur vulputate ullamcorper facilisis. Nullam euismod a quam sit amet sodales. Integer nunc elit, pharetra sed pulvinar quis, lacinia sit amet felis. Nunc sodales ex a ultricies placerat. Proin pharetra dapibus tortor, porta tristique ex volutpat sit amet. Pellentesque non nibh vel magna sagittis dignissim. Morbi dapibus imperdiet pellentesque. Ut convallis vel tellus eleifend dapibus.
          Cras placerat libero id velit hendrerit, ac mollis metus rhoncus. Maecenas vel accumsan lacus. Nunc congue ultricies sapien a porttitor. Vestibulum fringilla risus ac nibh feugiat, ultrices volutpat dolor tincidunt. Nulla scelerisque ipsum sit amet velit accumsan tincidunt. Aliquam a nibh efficitur, sodales ipsum sed, efficitur dui. In maximus purus in lectus ornare tristique. Nam faucibus porta nulla quis tempus. Etiam tristique sollicitudin euismod. Vivamus hendrerit sem et sem consectetur fermentum. Sed fermentum leo euismod augue tincidunt imperdiet. Aliquam et tempus felis, eu posuere nisl. Nullam a vestibulum dui. Nullam ut arcu id lorem tincidunt ullamcorper.
          Mauris vitae lectus id mi tincidunt bibendum. Sed sollicitudin consequat augue, a posuere tellus eleifend et. Pellentesque pharetra turpis diam, id suscipit nisi tincidunt eu. Etiam id ex vitae libero cursus finibus. Mauris varius ornare augue eget faucibus. Sed sodales magna a eros auctor, ac iaculis nisl sagittis. In gravida nulla aliquam eros sodales, nec tincidunt lectus cursus. Donec sit amet bibendum urna. Nulla sit amet urna at purus rhoncus congue et et magna. Sed volutpat sem ac justo pellentesque, facilisis aliquet lorem mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim fringilla tortor, sed tincidunt lectus facilisis quis. Nam ultrices tincidunt turpis, non tempor dui placerat a.
          Quisque posuere metus a mauris mollis, iaculis lacinia purus accumsan. Integer ut enim et felis commodo aliquet. Curabitur congue erat odio, a gravida justo luctus eget. Donec sollicitudin vestibulum turpis. Curabitur condimentum enim at turpis dapibus, in vehicula leo fringilla. Donec non tortor lacus. Nullam cursus fringilla iaculis. Sed dolor ipsum, congue eget dui quis, varius luctus nisl. Sed massa lacus, sodales non ultricies in, mollis ac dui. Etiam urna elit, convallis non neque quis, mattis pharetra erat. Curabitur at augue quis arcu venenatis tristique quis eu orci. Fusce malesuada iaculis nulla id elementum. Praesent quis nulla lacinia, bibendum dolor quis, finibus diam. Phasellus interdum augue at orci ultricies viverra.
          Donec hendrerit, orci vel vehicula laoreet, enim urna euismod odio, quis gravida mauris nisl nec nulla. In massa velit, hendrerit non nisi at, placerat tempor eros. Aliquam ut mollis nisi, ut congue tellus. Morbi aliquam massa nec arcu mollis tincidunt. Ut sed dui quis massa sollicitudin molestie. Maecenas et dignissim elit. Etiam a placerat elit. Nam tincidunt, massa ac rutrum vulputate, sapien diam blandit sem, vitae dictum enim lacus et nibh. Praesent pharetra gravida vehicula. Aenean purus massa, ullamcorper id felis vestibulum, tincidunt lobortis dui. Vestibulum iaculis pretium nulla. Vestibulum quis ex non dolor bibendum efficitur quis sed tortor. Aliquam viverra erat in tellus venenatis ultricies in facilisis ligula. Integer maximus porta tortor, eget venenatis lorem auctor ut. Praesent tristique nibh eu semper aliquam.
          Proin rhoncus ut orci non rutrum. Fusce sodales lacus ac arcu aliquet consequat. Sed auctor mi eget elementum gravida. Phasellus tempor quis lorem a varius. Curabitur malesuada, eros ac dictum consequat, elit augue tincidunt odio, sit amet malesuada odio tortor eu velit. Fusce tincidunt porta libero, eget aliquam purus lacinia nec. Phasellus rutrum ipsum a blandit cursus.
          Morbi a mauris non neque elementum condimentum. Donec convallis finibus dolor, ut gravida metus. Fusce ut sapien vel turpis cursus dictum id at risus. Ut vulputate libero ligula. Integer mollis, tellus eu pretium interdum, nibh ante eleifend ante, nec imperdiet nisl tortor at dui. Aliquam id ornare erat. Phasellus dignissim feugiat augue, sed aliquet tortor porta ut. Duis condimentum maximus lacus, sit amet fringilla leo cursus a. Proin sed ullamcorper nisl. Sed sagittis nisl nunc, ac maximus risus efficitur in. Praesent suscipit eleifend tellus, ac dignissim ante consequat at. Donec suscipit et risus ac faucibus.
      </p>

    </>
  )
}
